### ISSUE TITLE
Importing pyatmos raises ModuleNotFoundError: No module named 'numba'

### ISSUE THREAD

**Issue by volkswagenfeature** [lcx366/ATMOS#1]
Seems like you just forgot to put it in the requirements file?
(or maybe it's just my machine)
Probably a easy fix.

**Comment by lcx366** [comment]
Yes, I did forget to add `numba`. I have fixed the problem on Github, but it has not yet been published on PyPI.

**Comment by volkswagenfeature** [comment]
Ok, cool. Thanks for the info!
